// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'color-blue': string;
  'redText': string;
  'small_text': string;
}
export const cssExports: CssExports;
export default cssExports;
